version: '3.3'
services:
  nginx:
    image: "nginx:latest"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:80"
    networks:
      - test
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-demo:1.0.0
    container_name: flask
    networks:
      - test
networks: 
  test: